### PR TITLE
Dash 12.1 support

### PR DESCRIPTION
**Pull request by uzyn**
Updated to support Dash 12.1

### CODE REVIEW

**Comment by schinzelh** [comment]
You are a star, many thanks!

**Comment by uzyn** [comment]
Thanks. This is part of the work from https://www.dashcentral.org/p/tenx-dash-debit-card .

**Comment by schinzelh** [comment]
Cool, the updated image should be available on dockerhub in some minutes.

**Comment by uzyn** [comment]
Thanks @schinzelh 

Oops, just submitted another one (#6)  to add testnet support. I feel that's quite essential to allow devs to work on testnet easily using this docker image without having to custom-build one.

**Pull request merged**
