### PR TITLE
chore: update to Dash Core v0.16.1.1

### PR DESCRIPTION
**Pull request by thephez**
Noticed this was a little behind.
@pastapastapasta Updating this should maybe be added as a post-release step in the release process.

### CODE REVIEW

**Review by UdjinM6 — APPROVED** [review]
👍

**Comment by thephez** [comment]
I don't have the ability to merge so someone else will need to complete that. Maybe @UdjinM6 or @strophy? Does CI handle pushing a new image to Docker Hub?

**Comment by nmarley** [comment]
I know it used to automatically (via Docker Hub) but they changed the automation about a year and a half or 2 ago and it stopped working. I started building and pushing them manually after that.

**Comment by UdjinM6** [comment]
🤷‍♂️

**Pull request merged**
